services:
  productservice:
    build: ./ProductService
    container_name: productservice
    ports:
      - "5001:8080"

  customerservice:
    build: ./CustomerService
    container_name: customerservice
    ports:
      - "5002:8080"

  orderservice:
    build: ./OrderService
    container_name: orderservice
    ports:
      - "5003:8080"

  gateway:
    build: ./Gateway
    container_name: gateway
    ports:
      - "8000:8080"
    depends_on:
      - productservice
      - customerservice
      - orderservice
